name: publish

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - run: npm run build
      - run: npm run docs
      - run: npm test

      - run: npm publish
        working-directory: ./lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push docs to ghpages
        run: |
          set -x

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          TEMP_DIR=$(mktemp -d)
          mv ./docs $TEMP_DIR

          git fetch origin ghpages:ghpages
          git checkout ghpages
          git rm -rf .
          git clean -fxd
          
          cp -R $TEMP_DIR/docs/. .

          git add .
          git commit -m "Updated docs ($(git rev-parse --short $GITHUB_SHA))"
          git push origin ghpages

      - run: gh release create ${{ github.ref_name }} --generate-notes --draft
        env:
          GH_TOKEN: ${{ github.token }}
